services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Syncs your local folder to the container (Live Reloading!)
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=secret

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists DB data even if container dies
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

volumes:
  postgres_data: