services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  web:
    build: .
    # COMMAND CHANGED: We now collect static files automatically on startup!
    command: sh -c "python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Write CSS here
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=secret

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Load our custom config
      - ./frontend/index.html:/usr/share/nginx/html/index.html # Load frontend
      - static_volume:/app/staticfiles # Read CSS from here
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: # Shared storage for CSS files